name: Data Pipeline

on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight
  workflow_dispatch:

jobs:
  process-data:
    runs-on: ubuntu-latest
    env:
      BHUVAN_API_KEY: ${{ secrets.BHUVAN_API_KEY }}
      VEDAS_API_KEY: ${{ secrets.VEDAS_API_KEY }}
      
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Data Processor
      run: python data_processor.py
      
    - name: Commit and Push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Automated data update"
        git push
